modLoader="javafml"
loaderVersion="[31,)"
updateJSONURL="https://tophat.cat/red-pandas/update.json"
issueTrackerURL="https://github.com/tophatcats-mods/red-pandas/issues"
displayURL="https://tophat.cat/red-pandas/"
license="GNU Lesser General Public License 2.1"
logoFile=""
credits="ProxyNeko"
authors="ProxyNeko"

[[mods]]
modId="redpandas"
version="${file.jarVersion}"
displayName="Red Pandas"
description='''
A small mod with just Red Pandas coz why not they are so cute!
'''

[[dependencies.redpandas]]
   modId="forge"
   mandatory=true
   versionRange="[31,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.redpandas]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.15,]"
   ordering="NONE"
   side="BOTH"